# Generated by Django 4.2.5 on 2023-09-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('slot_id', models.IntegerField()),
                ('unlocked', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
