# Generated by Django 4.2.5 on 2023-10-07 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_attendanceslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('slot_id', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ma_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
